/* Privacy policies imported VERBATIM from the published documents behind each
   Play Store listing (kaushalbahl007.github.io/...). This text must stay aligned
   with what users see on Google Play — summarise it and the two fall out of sync. */
export const policies = {
  'arrow-puzzle': {
    updated: 'July 12, 2026',
    sections: [
      { h: 'Privacy Policy', body: [
        ['lab', 'This Privacy'],
        ['p', 'Policy explains how "Arrows Puzzle Escape" ("the app", "we") handles information when you play. The app is free to play, supported by ads, and does not require an account.'],
      ]},
      { h: 'Information We Collect', body: [
        ['p', 'We do not collect any personal information such as your name, email address, or phone number. Your game progress (completed levels, stars, points, and coins) is stored only on your device and is never sent to us.'],
      ]},
      { h: 'Advertising', body: [
        ['p', 'The app shows ads through Google AdMob , an advertising service provided by Google LLC. To serve and measure ads, Google may automatically collect and process the following from your device:'],
        ['li', 'Device or other IDs — your device\'s Advertising ID'],
        ['li', 'Approximate location — estimated from your IP address (the app never uses GPS)'],
        ['li', 'App interactions — such as ad views and clicks'],
        ['p', 'This data is used solely for advertising and marketing purposes and is always transmitted encrypted. You can read how Google handles this data in the Google Privacy Policy and Google\'s Ad Policy.'],
      ]},
      { h: 'Your Choices', body: [
        ['p', 'You can reset or delete your device\'s Advertising ID, or opt out of personalized ads, at any time in your device settings:'],
        ['p', 'Settings  Privacy  Ads.'],
      ]},
      { h: 'Notifications', body: [
        ['p', 'The app may show local reminder notifications. These are generated entirely on your device and involve no data collection. You can turn them off any time in your device\'s notification settings.'],
      ]},
      { h: 'Children', body: [
        ['p', 'The app is intended for a general audience and is not directed at children under 13. We do not knowingly collect personal information from children.'],
      ]},
      { h: 'Security', body: [
        ['p', 'We value your trust. The app itself sends no personal data anywhere, and all data transmitted by our advertising partner is encrypted in transit.'],
      ]},
      { h: 'Changes to This Policy', body: [
        ['p', 'We may update this Privacy Policy from time to time. Changes will be posted on this page with a new revision date.'],
      ]},
      { h: 'Contact', body: [
        ['p', 'If you have any questions about this Privacy Policy, contact us:'],
        ['p', 'kaushalbahl007@email.com © 2026 Arrows Puzzle Escape. All rights reserved.'],
      ]},
    ],
  },
  'flowpath': {
    updated: 'April 18, 2026',
    sections: [
      { h: 'Privacy Policy', body: [
        ['p', 'Flowpath is a free puzzle game. We are committed to protecting your privacy.'],
        ['p', 'This policy explains what information is collected, how it is used, and your choices.'],
      ]},
      { h: 'Information We Collect', body: [
        ['p', 'Flowpath itself does not collect, store, or transmit any personally identifiable information (PII). However, third-party services integrated into the app may collect certain data as described below.'],
        ['p', 'Data collected automatically by third-party SDKs:'],
        ['li', 'Device identifiers (advertising ID, device model, OS version)'],
        ['li', 'IP address and approximate location (country/region level)'],
        ['li', 'Ad interaction data (impressions, clicks, conversions)'],
        ['li', 'App usage and performance diagnostics'],
      ]},
      { h: 'Google AdMob', body: [
        ['p', 'Flowpath uses Google AdMob to display advertisements.'],
      ]},
      { h: 'Game Progress Data', body: [
        ['p', 'Your game progress is stored locally on your device only.'],
      ]},
      { h: 'Advertising IDs', body: [
        ['p', 'We use the Google Advertising ID solely for ads.'],
      ]},
      { h: 'Children\'s Privacy', body: [
        ['p', 'Not directed to children under 13.'],
      ]},
      { h: 'Data Sharing', body: [
        ['p', 'We do not sell or share user data.'],
      ]},
      { h: 'Data Security', body: [
        ['p', 'Data is stored locally on your device.'],
      ]},
      { h: 'Your Rights & Choices', body: [
        ['li', 'Opt out of ads in device settings'],
        ['li', 'Reset Advertising ID'],
        ['li', 'Delete data by uninstalling app'],
      ]},
      { h: 'Third-Party Links', body: [
        ['p', 'We are not responsible for third-party sites.'],
      ]},
      { h: 'Changes to This Policy', body: [
        ['p', 'We may update this policy anytime.'],
      ]},
      { h: 'Contact Us', body: [
        ['p', 'App: Flowpath Developer: Flowpath Games Email:'],
        ['p', 'flowpathgame@gmail.com kaushalbahl007@gmail.com © 2026 Flowpath Games. All rights reserved.'],
      ]},
    ],
  },
  'ludo': {
    updated: 'April 2026',
    sections: [
      { h: 'Privacy Policy', body: [
        ['lab', 'Ludo Indian'],
        ['p', 'Edition ("we", "our", or "us") operates the Ludo Indian Edition mobile application (the "App").'],
        ['p', 'This page explains how we collect, use, and protect user information while using our application.'],
      ]},
      { h: 'Information Collection and Use', body: [
        ['p', 'We may automatically collect limited information to improve gameplay experience and app performance, including:'],
        ['li', 'Device information (device model, operating system version)'],
        ['li', 'Usage data (game activity, session duration)'],
        ['li', 'IP address and diagnostic information'],
        ['p', 'This information helps us maintain stability, improve performance, and enhance user experience.'],
      ]},
      { h: 'Third-Party Services', body: [
        ['p', 'Our application may use trusted third-party services which may collect information according to their own privacy policies:'],
        ['li', 'Google AdMob — for advertisements'],
        ['li', 'Google Firebase — for analytics and crash reporting'],
      ]},
      { h: 'Advertising', body: [
        ['p', 'We use Google AdMob to display advertisements within the app. AdMob may use cookies, advertising identifiers, and device information to show personalized or non-personalized ads.'],
        ['p', 'Learn more about Google\'s advertising policies here:'],
        ['p', 'https://policies.google.com/technologies/ads'],
      ]},
      { h: 'Data Security', body: [
        ['p', 'We value your trust and strive to use commercially acceptable methods to protect your information.'],
        ['p', 'However, no internet transmission or storage system is completely secure.'],
      ]},
      { h: 'Children’s Privacy', body: [
        ['p', 'This application does not knowingly collect personal information from children under the age of 13.'],
        ['p', 'If we discover such information has been collected, it will be removed immediately.'],
      ]},
      { h: 'Changes to This Privacy Policy', body: [
        ['p', 'We may update this Privacy Policy periodically. Any changes will be posted on this page with an updated effective date.'],
      ]},
      { h: 'Contact Us', body: [
        ['p', 'If you have any questions or concerns regarding this Privacy Policy, please contact us:'],
        ['p', 'Email:'],
        ['p', 'kaushalbahl007@gmail.com © 2026 Ludo Indian Edition. All Rights Reserved.'],
      ]},
    ],
  },
  'block-burst': {
    updated: 'May 15, 2026',
    sections: [
      { h: 'Privacy Policy', body: [
        ['p', 'Block Burst · Benzene Studio · Effective May 15, 2026 No Personal Data Collected No Account Required GDPR Friendly No Login Play instantly. No account or email needed.'],
        ['lab', 'No Tracking'],
        ['p', 'We don\'t track you across apps or websites.'],
        ['lab', 'Local Storage'],
        ['p', 'Your progress stays only on your device.'],
        ['lab', 'Ads Present'],
        ['p', 'Google AdMob used. Removable via purchase.'],
        ['p', '1'],
      ]},
      { h: 'Introduction', body: [
        ['p', 'Block Burst is a casual mobile block puzzle game developed by Benzene Studio.'],
        ['lab', 'This Privacy'],
        ['p', 'Policy describes our practices regarding information when you use our Game on Android devices.'],
        ['p', 'We believe privacy is a fundamental right. This policy is written in plain language so you know exactly what happens with any data related to your use of Block Burst.'],
        ['p', '2'],
      ]},
      { h: 'Information We Collect', body: [
        ['p', 'What we do NOT collect:'],
        ['li', 'Your name, email address, or any personal identifiers'],
        ['li', 'Phone number or device contacts'],
        ['li', 'Location or GPS data'],
        ['li', 'Camera, microphone, or photo library access'],
        ['li', 'Social media profiles or login credentials'],
        ['li', 'Browsing history or cross-app activity'],
        ['p', 'What is stored locally on your device only:'],
        ['li', 'Game progress (scores, levels completed, achievements)'],
        ['li', 'App settings (sound, vibration, tutorial preferences)'],
        ['li', 'Daily mission progress and login streak count'],
        ['li', 'In-game coin balance and purchase status (Remove Ads)'],
        ['li', 'High score and leaderboard data (local only)'],
        ['p', 'Important: All of the above data is saved using Android\'s local SharedPreferences storage on your device. It is never transmitted to any external server or database controlled by Benzene Studio.'],
        ['p', '3'],
      ]},
      { h: 'Advertising (Google AdMob)', body: [
        ['p', 'Block Burst displays advertisements provided by Google AdMob. These ads help us keep the game free. AdMob may collect and use certain data to show you relevant ads.'],
        ['p', 'Types of ads shown:'],
        ['li', 'Banner Ads — small ads shown at the bottom of the home screen'],
        ['li', 'Interstitial Ads — full-screen ads shown between game sessions (every few games)'],
        ['li', 'Rewarded Ads — optional ads you can watch to earn in-game benefits (e.g. continue playing)'],
        ['p', 'Google AdMob may use device identifiers (such as Advertising ID) and other signals to personalise ads.'],
        ['p', 'You can opt out of personalised advertising in your device settings under Google  Ads  Delete advertising ID or by disabling ad personalisation.'],
        ['p', 'Learn more at policies.google.com/privacy.'],
        ['p', 'You can permanently Remove Ads via the in-app purchase option in the Shop screen for a one-time fee of $2.99. After purchasing, all banner and interstitial ads are disabled. Optional rewarded ads remain available as they provide direct in-game benefits at your choice.'],
        ['p', '4'],
      ]},
      { h: 'In-App Purchases', body: [
        ['p', 'Block Burst offers optional in-app purchases (coin packs, Remove Ads). All payment transactions are processed securely by Google Play Billing. Benzene Studio does not collect, store, or have access to your payment card information at any time.'],
        ['li', 'Payments processed entirely by Google Play'],
        ['li', 'We only receive confirmation that a purchase was made'],
        ['li', 'No financial data is stored by us'],
        ['li', 'Purchases are non-refundable except as required by applicable law'],
        ['p', '5'],
      ]},
      { h: 'Third-Party Services', body: [
        ['p', 'The following third-party services are used in Block Burst:'],
        ['li', 'Google AdMob — for displaying advertisements ( Privacy Policy )'],
        ['li', 'Google Play Billing — for processing in-app purchases ( Privacy Policy )'],
        ['li', 'Android Push Notifications — local device-only reminders (no server involved)'],
        ['p', 'Benzene Studio does not use Firebase, analytics SDKs, crash reporting tools, or any other third-party data collection services beyond those listed above.'],
        ['p', '6'],
      ]},
      { h: 'Children\'s Privacy', body: [
        ['p', 'Block Burst is a family-friendly game suitable for all ages. We do not knowingly collect personal information from children under 13 (or the applicable age in your jurisdiction).'],
        ['p', 'Since we do not collect any personal information from any user, there is no special risk to younger players beyond the ad content shown by Google AdMob, which follows Google\'s own child-directed treatment policies.'],
        ['p', '7'],
      ]},
      { h: 'Data Security', body: [
        ['p', 'Since all game data is stored locally on your device using Android\'s built-in storage mechanisms, security is maintained by your device\'s own operating system protections (PIN, biometrics, encryption).'],
        ['p', 'Benzene Studio does not operate any servers that store your personal data, so there is no risk of a server-side data breach exposing your information.'],
        ['p', '8'],
      ]},
      { h: 'Your Rights', body: [
        ['p', 'Depending on your location, you may have rights including:'],
        ['li', 'Right to know what data is collected about you'],
        ['li', 'Right to delete your data — simply uninstall the game to remove all local data'],
        ['li', 'Right to opt out of personalised advertising — via Android device settings'],
        ['li', 'Right to request information about data practices — contact us below'],
        ['p', 'To delete all your data: Uninstall Block Burst from your device. All locally stored game data (progress, settings, scores) will be permanently removed.'],
        ['p', '9'],
      ]},
      { h: 'Changes to This Policy', body: [
        ['p', 'We may update this Privacy Policy from time to time. Any changes will be reflected with a new effective date at the top of this page. We encourage you to review this policy periodically.'],
        ['p', 'Continued use of Block Burst after any changes constitutes acceptance of the updated Privacy Policy.'],
      ]},
      { h: 'Questions or Concerns?', body: [
        ['p', 'If you have any questions about this Privacy Policy or our data practices, please contact us.'],
        ['p', 'kaushalbahl007@gmail.com Benzene Studio · Block Burst · We aim to respond within 48 hours Block Burst — Privacy Policy · Effective May 15, 2026 © 2026 Benzene Studio. All rights reserved.'],
        ['p', 'This policy applies to the Android version of Block Burst available on Google Play.'],
      ]},
    ],
  },
  'marble-ball-sort': {
    updated: 'May 16, 2026',
    sections: [
      { h: 'Privacy Policy', body: [
        ['p', 'Tube Sort Puzzle Effective Date: May 16, 2026 Last Updated: May 16, 2026 SECTION 01'],
      ]},
      { h: 'Introduction', body: [
        ['p', 'Welcome to Tube Sort Puzzle ("the Game"), developed and published by Kaushal Kumar ("we", "us", or "our").'],
        ['lab', 'This Privacy'],
        ['p', 'Policy explains how we collect, use, and protect information when you play our mobile game available on the Google Play Store.'],
        ['p', 'By downloading and playing Tube Sort Puzzle, you agree to the terms described in this Privacy Policy.'],
        ['p', 'SECTION 02'],
      ]},
      { h: 'Information We Collect', body: [
        ['p', 'We do NOT directly collect:'],
        ['li', 'Your name, email address, or personal identification'],
        ['li', 'Location or GPS data'],
        ['li', 'Camera or microphone access'],
        ['li', 'Contacts or phone data'],
        ['li', 'Financial or payment information'],
        ['p', 'Automatically collected via third-party services:'],
        ['li', 'Device model, OS version, and unique device identifiers'],
        ['li', 'Gameplay events (levels completed, session length)'],
        ['li', 'Crash reports and performance data'],
        ['li', 'Advertising Identifier (GAID) for displaying ads'],
        ['p', 'SECTION 03'],
      ]},
      { h: 'Third-Party Services', body: [
        ['p', 'Tube Sort Puzzle integrates the following third-party services. Each has its own privacy policy and data practices:'],
        ['lab', 'Service Purpose Privacy Policy Google'],
        ['p', 'AdMob Displaying banner advertisements View Policy Google Play Services App delivery, updates, and analytics View Policy We do not control how these third-party services use collected data. We encourage you to review their policies.'],
        ['p', 'SECTION 04'],
      ]},
      { h: 'Advertising', body: [
        ['p', 'Our game displays banner advertisements powered by Google AdMob. AdMob may use your Advertising ID to show personalized or non-personalized ads based on your preferences.'],
        ['p', 'To opt out of personalized ads on Android:'],
        ['li', 'Open Settings on your Android device'],
        ['li', 'Tap Google  Ads'],
        ['li', 'Enable "Opt out of Ads Personalization"'],
        ['p', 'SECTION 05'],
      ]},
      { h: 'Data Storage', body: [
        ['p', 'All your game progress is stored locally on your device only. This includes:'],
        ['li', 'Levels completed and current level'],
        ['li', 'Stars earned and spent'],
        ['li', 'Tube skins unlocked and active skin'],
        ['li', 'Game settings and preferences'],
        ['p', 'We do not upload your game data to any external server or cloud service.'],
        ['p', 'SECTION 06'],
      ]},
      { h: 'Children\'s Privacy', body: [
        ['lab', 'Tube Sort'],
        ['p', 'Puzzle is suitable for all ages, including children. We do not knowingly collect personal information from children under the age of 13.'],
        ['p', 'If you are a parent or guardian and believe your child has provided personal data to us, please contact us immediately at the email below and we will take steps to delete such information promptly.'],
        ['p', 'SECTION 07'],
      ]},
      { h: 'Data Security', body: [
        ['p', 'We take reasonable precautions to protect your information. Since all game data is stored locally on your device, the security of your data depends largely on your device\'s own security settings and protections.'],
        ['p', 'We recommend keeping your device software up to date and using a secure screen lock.'],
        ['p', 'SECTION 08'],
      ]},
      { h: 'Your Rights', body: [
        ['p', 'You have the following rights regarding your data:'],
        ['li', 'Access — Request information collected about you by third-party services by contacting them directly'],
        ['li', 'Opt Out — Disable personalized advertising via your device settings'],
        ['li', 'Delete — Remove all local game data by uninstalling the application'],
        ['li', 'Contact — Reach out to us with any privacy concerns at any time'],
        ['p', 'SECTION 09'],
      ]},
      { h: 'Changes to This Policy', body: [
        ['p', 'We may update this Privacy Policy from time to time to reflect changes in our practices or for legal reasons. When we do:'],
        ['li', 'The "Last Updated" date at the top will be revised'],
        ['li', 'Significant changes will be noted in the Google Play Store listing'],
        ['li', 'Continued use of the game after changes means you accept the updated policy'],
        ['p', 'SECTION 10'],
      ]},
      { h: 'Contact Us', body: [
        ['p', 'If you have any questions, concerns, or requests regarding this Privacy Policy, please don\'t hesitate to reach out:'],
        ['p', '‍ Kaushal Kumar kaushalbahl007@gmail.com com.tubesort.puzzle · Tube Sort Puzzle © 2026 Tube Sort Puzzle · All rights reserved This privacy policy applies solely to the Tube Sort Puzzle application.'],
        ['p', 'Package: com.tubesort.puzzle'],
      ]},
    ],
  },
  'snake-tangle': {
    updated: 'May 2026',
    sections: [
      { h: 'Overview', body: [
        ['p', 'Snake Tangle ("we", "our", or "the App") is a mobile arcade game developed for Android. We are committed to protecting your privacy and being fully transparent about the data practices of our application.'],
        ['p', 'Short version: We do not collect, store, or sell your personal information.'],
        ['p', 'The app stores game progress locally on your device only. Third-party advertising SDKs (Google AdMob) may collect limited data as described below.'],
        ['p', 'By downloading, installing, or using Snake Tangle, you agree to the terms of this Privacy Policy. If you do not agree, please do not use the application.'],
      ]},
      { h: 'Data We Collect', body: [
        ['p', 'We collect the minimum data necessary to provide a great gaming experience.'],
        ['lab', 'Game Progress (Local Storage Only)'],
        ['p', 'High scores, star ratings, level completions, achievements, and settings are saved locally on your device using SharedPreferences. This data never leaves your device and is not transmitted to any server.'],
        ['lab', 'Notification Preferences'],
        ['p', 'If you grant notification permission, we store a local preference to schedule reminder notifications. No notification data is sent to external servers.'],
        ['lab', 'Advertising Data (via Google AdMob)'],
        ['p', 'Our third-party ad partner Google AdMob may collect device identifiers, IP address, and usage data to serve personalised or contextual advertisements. See Section 3 for full details.'],
        ['lab', 'What We Do NOT Collect'],
        ['p', 'We do not collect your name, email address, phone number, location data, contacts, photos, microphone input, camera data, payment information, or any other personal identifiers.'],
        ['p', 'Local Storage No Account Required No Server Upload AdMob Data'],
      ]},
      { h: 'Advertising (Google AdMob)', body: [
        ['p', 'Snake Tangle is a free app supported by advertising. We use Google AdMob (provided by Google LLC) to display banner ads, interstitial ads, and rewarded video ads.'],
        ['lab', 'Banner Ads'],
        ['p', 'Small banner advertisements displayed at the bottom of screens including the home screen, settings, level select, and game over screens.'],
        ['lab', 'Interstitial Ads'],
        ['p', 'Full-screen advertisements that appear between gameplay sessions (e.g., after a game ends). These are shown periodically, not after every game.'],
        ['lab', 'Rewarded Video Ads'],
        ['p', 'Optional video advertisements you can choose to watch in exchange for a free continue after a game over. These are entirely voluntary.'],
        ['p', 'ℹ Google AdMob may collect and use data including: Advertising ID, IP address, device type, OS version, app usage data, and coarse location to deliver targeted advertisements. This data is governed by Google\'s Privacy Policy : policies.google.com/privacy You can opt out of personalised advertising at any time by visiting Settings  Google  Ads  Opt out of Ads Personalisation on your Android device.'],
      ]},
      { h: 'App Permissions', body: [
        ['p', 'Snake Tangle requests the following Android permissions:'],
        ['p', 'INTERNET Required to load and display advertisements from Google AdMob. The app does not send any personal data over the internet beyond what AdMob requires.'],
        ['p', 'POST_NOTIFICATIONS Required on Android 13+ to show local reminder notifications. We only send notifications to remind you to play — no marketing or third-party messages.'],
        ['p', '⏰ SCHEDULE_EXACT_ALARM / USE_EXACT_ALARM Required to schedule precise local reminder notifications (e.g., "come back and play" after 2 hours of inactivity). No data is transmitted.'],
        ['p', 'ACCESS_NETWORK_STATE Used by the AdMob SDK to check network availability before loading ads, preventing unnecessary failures.'],
        ['p', 'RECEIVE_BOOT_COMPLETED Allows scheduled local notifications to be re-registered after the device reboots, so reminders remain active.'],
        ['p', 'We do not request: Camera, Microphone, Contacts, Location (fine or coarse from our app), SMS, Call Logs, or any other sensitive permission.'],
      ]},
      { h: 'Children\'s Privacy (COPPA)', body: [
        ['p', 'Snake Tangle is rated for audiences aged 3 and above on Google Play.'],
        ['p', 'The application is designed to be family-friendly and safe for children.'],
        ['p', 'Important: This app contains advertisements served by Google AdMob.'],
        ['p', 'Advertisements shown to users known to be under 13 will be non-personalised (contextual only), in compliance with the Children\'s Online Privacy Protection Act (COPPA) and Google\'s Families Policy.'],
        ['p', 'We do not knowingly collect personal information from children under 13. The app does not include chat features, social networking, user-generated content, or any feature that would allow a child to share personal information.'],
        ['p', 'If you are a parent or guardian and believe your child has provided personal information to us, please contact us immediately at the address below and we will delete such data promptly.'],
        ['p', 'COPPA Compliant No In-App Chat Family Safe Rated 3+'],
      ]},
      { h: 'Data Sharing & Third Parties', body: [
        ['p', 'We do not sell, trade, or rent your personal information to any third party.'],
        ['p', 'Google AdMob (Alphabet Inc.)'],
        ['p', 'Our only third-party SDK. Receives advertising-related data to serve ads. Governed by Google\'s Privacy Policy and Terms of Service. AdMob App ID: ca-app-pub-4838625043093831.'],
        ['lab', 'Legal Compliance'],
        ['p', 'We may disclose information if required by law, court order, or governmental authority. We will always seek to minimise such disclosure.'],
        ['lab', 'No Other Sharing'],
        ['p', 'We have no analytics SDKs (e.g., Firebase Analytics, Crashlytics), no social media integrations, no marketing platforms, and no data brokers integrated into the application.'],
      ]},
      { h: 'Your Rights & Controls', body: [
        ['p', 'You have full control over your data. Here is what you can do:'],
        ['lab', 'Delete All Local Data'],
        ['p', 'Open the app  Settings  Reset Progress. This permanently deletes all locally stored game data including scores, stars, and achievements.'],
        ['lab', 'Disable Notifications'],
        ['p', 'Go to your device Settings  Apps  Snake Tangle  Notifications  Disable. No reminder notifications will be sent.'],
        ['p', 'Opt Out of Personalised Ads Device Settings  Google  Ads  Opt out of Ads Personalisation. You will still see ads but they will be contextual, not targeted.'],
        ['p', 'Uninstall the App Uninstalling Snake Tangle removes all locally stored data from your device. No data remains on any server as we do not use one.'],
        ['lab', 'GDPR Rights (EU/UK Users)'],
        ['p', 'If you are located in the European Economic Area or United Kingdom, you have the right to access, rectify, erase, restrict, and object to processing of your personal data. Contact us using the details below.'],
        ['lab', 'CCPA Rights (California Users)'],
        ['p', 'California residents have the right to know what personal information is collected, the right to deletion, and the right to opt-out of sale. We do not sell personal information.'],
      ]},
      { h: 'Data Security', body: [
        ['p', 'We take reasonable steps to protect the information stored locally on your device.'],
        ['p', 'Since all game data is stored only on your device using Android\'s standard SharedPreferences storage:'],
        ['lab', 'On-Device Storage Only'],
        ['p', 'Your game data never leaves your device. There are no remote databases, cloud saves, or backup servers associated with Snake Tangle.'],
        ['lab', 'Android App Sandbox'],
        ['p', 'Data stored by the app is protected by Android\'s built-in application sandbox. Other apps cannot access Snake Tangle\'s stored data.'],
        ['lab', 'Encrypted Ad Communication'],
        ['p', 'All communication with Google AdMob servers uses HTTPS/TLS encryption, ensuring ad-related data is transmitted securely.'],
        ['p', 'No method of data storage or transmission is 100% secure. While we use commercially reasonable safeguards, we cannot guarantee absolute security. We recommend keeping your device OS and the app updated to benefit from the latest security patches.'],
      ]},
      { h: 'Changes to This Policy', body: [
        ['p', 'We may update this Privacy Policy from time to time. Changes will be posted on this page with an updated "Last updated" date at the top.'],
        ['p', 'For significant changes that materially affect your rights, we will notify you via a prominent notice within the application or through an app update description on Google Play.'],
        ['p', 'We recommend reviewing this policy periodically. Continued use of Snake Tangle after changes are posted constitutes your acceptance of the updated policy.'],
        ['p', 'Current version: 1.0 — May 2026.'],
      ]},
      { h: 'Contact Us', body: [
        ['p', 'If you have any questions, concerns, or requests regarding this Privacy Policy or your data, please do not hesitate to reach out. We aim to respond within 48 hours.'],
      ]},
      { h: 'SNAKE TANGLE SUPPORT', body: [
        ['p', 'Questions about privacy, data deletion, or policy clarification myselfkaushal.kumar@gmail.com ⏱ Response Time We typically respond to privacy inquiries within 48 hours on business days.'],
        ['p', 'Jurisdiction This app is developed and operated from India. By using the app, you consent to your data being processed in accordance with Indian data protection laws, as well as GDPR and CCPA where applicable.'],
        ['lab', 'SNAKE TANGLE Privacy'],
        ['p', 'Policy · Version 1.0 · May 2026 © 2026 Snake Tangle. All rights reserved.'],
        ['p', 'This document was created to comply with Google Play Store developer policies.'],
      ]},
    ],
  },
  'docsnap': {
    updated: 'July 17, 2026',
    sections: [
      { h: 'Privacy Policy', body: [
        ['p', 'DocSnap — PDF Scanner & Editor Last updated: July 17, 2026 This Privacy Policy explains how DocSnap ("the app", "we", "us") handles your information. DocSnap is a PDF scanner and editing tool that is designed to work offline and on your device. DocSnap is free to use and supported by ads. Please read this policy carefully. By using DocSnap, you agree to the practices described here.'],
        ['p', 'The short version: Your documents never leave your phone.'],
        ['p', 'DocSnap processes every scan, edit, merge, sign, and conversion locally on your device. We do not upload, store, sell, or share your files or their contents on any server. DocSnap is ad-supported — our advertising partner (Google AdMob) may collect device and advertising identifiers to show and measure ads, as described in Section 4 below.'],
      ]},
      { h: 'Information We Do Not Collect', body: [
        ['p', 'DocSnap does not collect, transmit, or store:'],
        ['li', 'The contents of your PDFs, scans, or images.'],
        ['li', 'Text extracted through OCR or search.'],
        ['li', 'Your signatures, annotations, passwords, or document metadata.'],
        ['li', 'Your name, email, phone number, or contacts.'],
        ['li', 'Your precise location.'],
        ['p', 'All documents you create or open, and any data derived from them, remain in the app\'s private storage on your device. If you uninstall the app, that data is removed with it.'],
      ]},
      { h: 'Information Processed On Your Device', body: [
        ['p', 'To provide its features, the app accesses certain data locally , without sending it anywhere:'],
        ['p', 'Feature What it accesses (on-device only) Document scanning Your camera, to capture pages you choose to scan.'],
        ['p', 'Import / Image  PDF Photos and files you explicitly select from your device.'],
        ['lab', 'Document Vault'],
        ['p', 'Your device biometric / screen-lock, only to unlock the vault. We never receive your fingerprint or PIN.'],
        ['p', 'Reminders Local notifications for document expiry dates you set. These are scheduled on the device.'],
        ['p', 'Search & OCR Text recognition runs on-device using Google ML Kit\'s on-device models.'],
      ]},
      { h: 'Permissions We Request', body: [
        ['p', 'Android may ask you to grant the following permissions. Each is used only for the stated purpose, and most are optional depending on which features you use:'],
        ['li', 'Camera — to scan documents. Used only while you are scanning.'],
        ['li', 'Photos / Storage — to let you import images or PDFs you choose, and to save your output files.'],
        ['li', 'Biometric — to unlock the optional Document Vault using your device\'s fingerprint / face / screen lock.'],
        ['li', 'Notifications — to show local reminders for document expiry dates you set.'],
        ['li', 'Internet / Network state — required to load and display ads (see below) and for the underlying app platform. The app does not upload your documents.'],
        ['li', 'Advertising ID (Android 13+: AD_ID permission) — used by our ad partner to serve and measure ads, and to let you opt out of personalized advertising in your device settings.'],
      ]},
      { h: 'Advertising', body: [
        ['p', 'DocSnap is free to use and is supported by ads shown via Google AdMob. Ads may appear as a banner within the app or as a full-screen / rewarded ad after certain actions. To select, serve, and measure ads — and to limit how often you see the same one — AdMob and its partners may collect and process:'],
        ['li', 'Your advertising ID and other device identifiers.'],
        ['li', 'General device information (device type, OS version, language, approximate/coarse location derived from IP).'],
        ['li', 'Ad interaction data (impressions, clicks, and similar engagement signals).'],
        ['p', 'This data is handled by Google, not by us — DocSnap does not send your documents, their contents, or any personal information you enter in the app to AdMob. You can review or reset your advertising ID, and opt out of personalized ads, in your device\'s Settings (Google Settings  Ads, or Privacy  Ads on newer Android versions). Google\'s use of this data is governed by Google\'s Privacy Policy and Google\'s EU User Consent Policy.'],
      ]},
      { h: 'Third-Party Services', body: [
        ['p', 'DocSnap relies on the following third-party components:'],
        ['lab', 'Google ML'],
        ['p', 'Kit (on-device) — powers text recognition (OCR) and document detection. Processing happens on your device; document text is not sent to Google for these features.'],
        ['p', 'Google AdMob — serves the in-app advertising described in Section 4 above.'],
        ['lab', 'Google Play'],
        ['p', 'Services / Play In-App Review — used for app distribution and to show Google Play\'s native "rate this app" prompt. This does not involve any purchase or payment feature — DocSnap has no paid tier.'],
        ['p', 'If a future version of the app introduces any service that transmits data off your device, we will update this policy and, where required, ask for your consent first.'],
      ]},
      { h: 'Data Sharing', body: [
        ['p', 'We — DocSnap the developer — do not sell, rent, or share your documents or their contents with anyone. The only time a document leaves the app is when you explicitly choose to share it — for example, using the Share button to send a file to another app (WhatsApp, email, cloud storage, etc.). At that point the receiving app\'s own privacy policy applies.'],
        ['p', 'Separately, as described in Section 4, our advertising partner Google AdMob automatically collects device and advertising identifiers to serve and measure ads. This is standard for ad-supported apps and does not include your documents or their contents.'],
      ]},
      { h: 'Data Security', body: [
        ['p', 'Your files are stored in the app\'s private, sandboxed storage that other apps cannot access. The optional Document Vault adds a biometric / screen-lock layer.'],
        ['p', 'For password-protected PDFs, encryption is applied on your device using industry- standard AES. Because no document data is transmitted to us, there is no server-side copy of your files to be breached.'],
      ]},
      { h: 'Children\'s Privacy', body: [
        ['p', 'DocSnap is a general-purpose productivity tool and is not directed to children under 13. We do not knowingly collect personal information from children.'],
      ]},
      { h: 'Your Rights & Control', body: [
        ['p', 'Because your data lives on your device, you are always in control. You can:'],
        ['li', 'Delete any document from within the app at any time.'],
        ['li', 'Revoke Camera, Photos, or Notification permissions in your device settings.'],
        ['li', 'Clear the app\'s cache from the app\'s Settings screen.'],
        ['li', 'Remove all app data by uninstalling DocSnap.'],
      ]},
      { h: 'Changes to This Policy', body: [
        ['p', 'We may update this Privacy Policy from time to time. When we do, we will revise the "Last updated" date at the top of this page. Significant changes will be reflected in the app or its store listing.'],
      ]},
      { h: 'Contact Us', body: [
        ['p', 'If you have questions about this Privacy Policy or how DocSnap handles your data, contact us at:'],
        ['p', 'Email: kaushal.kumar@gmail.com DocSnap — PDF Scanner & Editor · This policy applies to the DocSnap mobile application. © 2026 DocSnap. All rights reserved.'],
      ]},
    ],
  },
  'jyotish': {
    updated: 'July 2026',
    sections: [
      { h: 'Privacy Policy', body: [
        ['p', 'Jyotish — Vedic Astrology App Last updated: July 2026 Local Storage Only All your data stays on your device No Sign-in Required No account, no email needed No Data Selling We never sell your information Works Offline No server uploads ever 1'],
      ]},
      { h: 'Introduction', body: [
        ['p', 'Welcome to Jyotish , a Vedic astrology app built for privacy-first users. This Privacy Policy explains how we handle your information when you use our app.'],
        ['p', 'We built Jyotish with a simple principle: your birth data belongs to you, not us. Everything is calculated and stored locally on your device.'],
        ['p', '2'],
      ]},
      { h: 'Information We Collect', body: [
        ['p', 'The app asks you to enter the following information to generate your Kundli chart:'],
        ['p', 'Name · Date of birth · Time of birth · Place of birth (city/coordinates) This information is stored only on your device using local SQLite storage. It is never transmitted to any server, cloud, or third party by us.'],
        ['li', 'We do NOT upload your birth data to any server'],
        ['li', 'We do NOT require an account or email address'],
        ['li', 'We do NOT track your location in the background'],
        ['li', 'We do NOT use analytics SDKs to monitor your behavior'],
        ['li', 'We do NOT collect payment information'],
        ['p', '3'],
      ]},
      { h: 'How We Use Your Information', body: [
        ['p', 'The data you enter is used solely to:'],
        ['p', 'Calculate your Vedic birth chart · Generate Dasha periods · Show Panchang · Provide astrological guidance All calculations are performed entirely on your device using built-in mathematical algorithms. No internet connection is required for core features.'],
        ['p', '4'],
      ]},
      { h: 'Advertising (Google AdMob)', body: [
        ['p', 'Jyotish is a free app supported by advertisements. We use Google AdMob (by Google LLC) to serve ads, including banner ads, interstitial ads (shown between screens), and rewarded ads (shown before PDF export, share, or print actions — watching the ad is not required for these actions to complete). Google may independently collect:'],
        ['lab', 'Service Data Collected Privacy Policy'],
        ['p', 'Google AdMob Advertising ID, device identifiers, IP address, ad interactions, app activity (for ad targeting and fraud prevention) View Google Fonts IP address (font download) View We do not control what Google collects. You can opt out of personalized ads through your device settings: Settings  Google  Ads  Delete advertising ID.'],
        ['p', 'Learn more about how Google uses advertising data: policies.google.com/technologies/ads 5'],
      ]},
      { h: 'Data Storage & Security', body: [
        ['p', 'All your kundli profiles are stored in a local SQLite database on your device. We have zero access to this data — it never leaves your phone.'],
        ['p', 'If you uninstall the app, all your data is permanently deleted from your device. We cannot recover it because we never had it.'],
        ['p', 'We recommend backing up your device regularly using Android\'s built-in backup feature to avoid data loss.'],
        ['p', '6'],
      ]},
      { h: 'Data Sharing', body: [
        ['p', 'We do not sell, trade, rent, or otherwise transfer your personal information to any outside parties — ever.'],
        ['li', 'No data is sold to advertisers or data brokers'],
        ['li', 'No data is shared with analytics companies'],
        ['li', 'No data is transferred to any of our servers'],
        ['li', 'PDF exports are shared only when YOU choose to share them'],
        ['p', '7'],
      ]},
      { h: 'Children\'s Privacy', body: [
        ['p', 'Jyotish is not directed at children under the age of 13. We do not knowingly collect personal information from children. If you are a parent and believe your child has provided personal information through the app, please contact us and we will help address your concern.'],
        ['p', '8'],
      ]},
      { h: 'Your Rights', body: [
        ['p', 'Since all data is stored locally on your device, you have full control:'],
        ['p', 'Delete a profile  Open the app  Go to profiles  Delete. Your data is gone instantly and permanently.'],
        ['p', 'You can also uninstall the app at any time to remove all locally stored data.'],
        ['p', '9'],
      ]},
      { h: 'Changes to This Policy', body: [
        ['p', 'We may update this Privacy Policy from time to time. Any changes will be reflected on this page with an updated date at the top. We encourage you to review this page periodically.'],
        ['p', 'Continued use of the app after changes means you accept the updated policy.'],
      ]},
      { h: 'Questions or Concerns?', body: [
        ['p', 'If you have any questions about this Privacy Policy or how your data is handled, reach out to us directly.'],
        ['p', 'Contact Us Jyotish — Vedic Astrology © 2026 Jyotish App · All rights reserved Privacy Policy · Effective July 2026'],
      ]},
    ],
  },
}
